### ISSUE TITLE
Add Mesh loading from file

### ISSUE THREAD

**Issue by unpause** [JFrap/DregoEngine#6]
Would be very cool if we were able to load meshes from files :)

**Comment by JFrap** [comment]
Yea. we need to do it in a way so that a mesh can have multiple materials

**Comment by unpause** [comment]
Got the mesh loading working, loads a MeshResource which is a class with all the mesh data.

We just need a way to construct a Mesh from a MeshResource!

**Comment by JFrap** [comment]
Managed to get mesh loading and "Model" loading working, see earlier merge
